### ISSUE TITLE
More browsers

### ISSUE THREAD

**Issue by RyanRiffle** [RyanRiffle/Poe#22]
Right now webkit based browsers are the only ones that work correctly with the application. Figure out why firefox is acting funny and fix it. I do not have internet explorer so could somebody that does check it out?

**Comment by MrSchism** [comment]
On IE11, everything but the text drop-down worked for me.

**Comment by RyanRiffle** [comment]
@MrSchism Awesome! thank you :smile:

**Comment by MrSchism** [comment]
Not a problem.  No idea why the text dropdown didn't work, though.

**Comment by RyanRiffle** [comment]
I'm not sure. It just uses bootstrap.

**Comment by MrSchism** [comment]
Same issue exists on Firefox 30.0 (On Windows 8.1, 64-bit).  Also, the color selection for the font is busted.

**Comment by RyanRiffle** [comment]
@MrSchism Any way you can look into it a little more? I don't have a Windows machine available.

**Comment by MrSchism** [comment]
Yeah, I'll give it a shot.

**Comment by andersevenrud** [comment]
I'll have a go at testing tomorrow. A bit to late here atm. I have pretty much evey kind of machine at my disposal here. At the moment: Windows, Linux, OSX, iOS and Android :smile:

**Comment by MrSchism** [comment]
I have Windows and Linux at my disposal this weekend.

**Comment by RyanRiffle** [comment]
@MrSchism I have linux at my disposal. Windows 7 if I swap out the hard drives. It doesn't help either that my laptop is 8 years old, and missing half the keys on the keyboard. :stuck_out_tongue:
