### ISSUE TITLE
Ignores user's keyboard layout

### ISSUE THREAD

**Issue by quassy** [RyanRiffle/Poe#28]
As the title says: For me (German) this makes it impossible to enter äöü (Umlauts) as the app seems to be fixed onto a weird QWERTZ-English layout (why not QWERTY?).

**Comment by jakehh** [comment]
Is the code grabbing every keypress & inputting it into the DOM? I'm unable to use native shortcuts on OS X on the demo page. (when i can select a line of text it doesn't delete that text or it deletes the text infront of what i have selected)

I don't really understand the approach, But perhaps having native input could be a better approach for the input. This should allow any keyboard layout to be supported & should allow native shortcuts for all OS' & Browsers.

**Comment by RyanRiffle** [comment]
Native input is a no go. The way native input could almost possibly work is using text area with execCommand, but that generates different markup for each browser, so internal book keeping would be horrendous checking for for all of the different ways to accomplish the task, not to mention serialization of the data. 

I guess poe could use a off screen textArea or <input> then move over the text. I remember seeing that somewhere used on another project, maybe it was bespin (Ace).

**Comment by MrSchism** [comment]
That may actually resolve some other issues (like capturing tab) in the process.

**Comment by RyanRiffle** [comment]
@MrSchism I am working on this, but I am having problems getting the event to fire. It will fire an alert dialog but not my handler. :(
