### ISSUE TITLE
Suggestion - Line Numbers

### ISSUE THREAD

**Issue by MrSchism** [RyanRiffle/Poe#29]
I'd like to see line numbers added as a toggleable option.  It would add to the flexibility of the app.

If you don't want to add it, it'll take me a while to do (as I've got zero experience with CoffeeScript).  I'm assuming the work would be entirely in the Line.coffee file, but again... not 100% certain.

In the long run, I hope to have the lines be somewhat dynamic... showing the last line number with content having a highlight and (if possible) the current working line with a different numeric color.

Thoughts?

**Comment by RyanRiffle** [comment]
@MrSchism Do you mean line numbers like a code editor would have? If so It could be possible I am just unsure the use of it in a word processor. I do like the idea however, I don't remember seeing it in any other word processor: what value would it add? (namely in making what future features more usable?).

**Comment by MrSchism** [comment]
Yeah, lines like a code editor.  It would make it more flexible if it could double as a code editor.  If you have to do any light coding, it'd be easy to just turn on line numbers.

It also helps when you're looking at a file you want to manipulate with an external program (settings files, for example).

**Comment by RyanRiffle** [comment]
I'm sorry but adding features to double as a code editor to a word processor that is for essays and documents seems a little too much, but if you are up to the task by all means I wouldn't mind to see line numbers added. I would see them more useful though say using markdown or even better LaTex.

**Comment by RyanRiffle** [comment]
@MrSchism Just a note. Lines are actually Paragraph.coffee. Line.coffee is just a helper for word wrapping and page breaks. Each time the user presses enter a new paragraph is created, the lines are generated from word wrapping.

**Comment by MrSchism** [comment]
Alrighty.  I think I've made some progress on this.  I'm hoping to get a build environment set up here shortly, but I'm experiencing an issue.  I installed coffee-script and bower, but make isn't working.  Not sure why.

**Comment by RyanRiffle** [comment]
I am not sure. It works on my end. It might have to do where I have the makefile setup for me when i was working on the OSjs integration. Makefile line 22, I forgot to remove it when i committed changes. We'll get that fixed.

**Comment by RyanRiffle** [comment]
Try `make standalone`

**Comment by MrSchism** [comment]
Mind if I email you to see where I may potentially be going wrong?

**Comment by RyanRiffle** [comment]
That is fine with me. Send 'er on over

**Comment by RyanRiffle** [comment]
Implementing this is not where the project is headed. Having a gutter with line numbers seems to go against the purpose of a word processor. I think that feature is best left to code editors.
