### ISSUE TITLE
OS.js Integration

### ISSUE THREAD

**Issue by RyanRiffle** [RyanRiffle/Poe#31]
Needs to be integrated into OS.js project but only in a way that will still allow for it to be used without being completely dependent on that project (hopefully).
- [x] Get a window to show up with the editor
- [x] Create a common interface between OS.js toolbar and Poe's toolbar
- [ ] Get OS.js toolbar working well, (fonts, colors, text and paragraph formatting)
- [ ] PDF support in OS.js
- [ ] Refactor Poe.Writer and Poe.FontManager to allow font lists instead or with the loading of .ttf

**Comment by andersevenrud** [comment]
I can bring in PDF support to OS.js. What is the requirements ? Any specific library or formatting ?

**Comment by RyanRiffle** [comment]
Right now Poe uses [PDFKit](http://pdfkit.org/) a pretty good library. It is created for node, but can be used in the browser also by using blobs and browserify. The blobs though require use of [blob-stream](https://github.com/devongovett/blob-stream). To actually use it though you need access to font files (in order to embed them) or use a system font I believe. 

On the end of writing to the vfs it would have to be able to accept node streams like the blob-stream library does.

**Comment by RyanRiffle** [comment]
Or a node-stream API with a server "plugin" that creates the file then uses vfs put it in dropbox or wherever

**Comment by RyanRiffle** [comment]
Using PDFKit browser side along with blob-stream is about 1.5mb Its quite a bit.
