### ISSUE TITLE
Github Pages App 404'ing.

### ISSUE THREAD

**Issue by MrSchism** [RyanRiffle/Poe#34]
http://www.ryanriffle.github.io/Poe/demo/app.html is currently throwing a 404 error.

**Comment by RyanRiffle** [comment]
I wonder when that started... The hole github pages 404's including the documentation. The weird thing is that none of that was changed.

**Comment by MrSchism** [comment]
Found it.  Hang on.

**Comment by MrSchism** [comment]
Fixed the issue. in #35

**Comment by RyanRiffle** [comment]
@MrSchism That still does not fix it I don't think. If you open your browser and navigate to the updated url it still 404's. I believe it has to do with merge conflicts of index.html

**Comment by MrSchism** [comment]
Seems fixed to me.

I had only loaded it in Chrome... I loaded the new URL in firefox and IE and it worked.

**Comment by RyanRiffle** [comment]
Wow I wonder why that just started? Thank you!

**Comment by RyanRiffle** [comment]
@MrSchism You can view the [docs](http://www.ryanriffle.github.io/Poe/doc/) on the github pages also in case you didn't know

**Comment by MrSchism** [comment]
No idea, but it's the least I can do.

**Comment by RyanRiffle** [comment]
@MrSchism just pushed the updated docs
