### ISSUE TITLE
[Feature] RTF

### ISSUE THREAD

**Issue by RyanRiffle** [RyanRiffle/Poe#37]
Be able to read and write a RTF document through OSjs vfs api. The reason this is needed is because RTF is a simple format compared to ODF and MS Word .docx. This will allow for at least basic usage of Poe.

**Comment by andersevenrud** [comment]
So you know. OS.js uses ArrayBuffer to transfer and modify files. So this should make it rather simple :smile:

**Comment by RyanRiffle** [comment]
I figured a text file in OS.js would be a lot more simple. That is why I believe I am going to tackle this first. Not to mention it needs to be able to at least have some sort of saving and loading even if it is RTF

**Comment by andersevenrud** [comment]
Just convert to text. I have a method for that in vfs.js abToText or something

**Comment by andersevenrud** [comment]
OSjs has read() parameter for returning as text also

**Comment by RyanRiffle** [comment]
I wonder if PDFkit #31 can return an array buffer? I will have to see.

**Comment by andersevenrud** [comment]
@RyanRiffle OS.js supports these data types: Blob, File, ArrayBuffer, String, JSON:{filename: '', data: 'rawdata'}

VFS::write() can take any of those

VFS::read() here you can specify to return as text (default is ArrayBuffer. I can add support for all the above)

**Comment by RyanRiffle** [comment]
Nice. Well that will really be enough then. I can use PDFKit to genrate the pdf still, and when it comes time for odf and docx it will work also.
