### ISSUE TITLE
Building on Windows doesn't function properly

### ISSUE THREAD

**Issue by MrSchism** [RyanRiffle/Poe#38]
Building Poe on Windows 8.1 (64-bit) doesn't result in a site that works properly.  Tested on a node web server (via Brackets) and the python SimpleHTTPServer.

**Comment by andersevenrud** [comment]
What are you building on? The only "real" way to do this properly in windows is to use Cygwin or similar

**Comment by andersevenrud** [comment]
What are you building with? The only "real" way to do this properly in windows is to use Cygwin or similar

**Comment by MrSchism** [comment]
See, I wasn't entirely certain because node/coffee both install fine on Windows and I've done other node projects on it.  Coffee builds the files, but they don't seem to go right.  It almost seems like the CSS is broken.  The js files build (but I gotta check them against successful builds).

I might be able to make this work a bit better.

**Comment by andersevenrud** [comment]
Most Node packages will install just fine, but will not run properly on Windows platforms. Compability has been a problem for quite a while now.

That is why I mentioned Cygwin. If you do it that way you get around most of the problems you run into on a normal Windows setup.

**Comment by andersevenrud** [comment]
> It almost seems like the CSS is broken

Do you see any obvious errors in the compiled stylesheet ?

**Comment by RyanRiffle** [comment]
Since it is only a webpage, and viewing the demo on windows through chrome works fine, I doubt it would be a CSS issue. And can you give more details about "doesn't result in a site that works correctly"

**Comment by MrSchism** [comment]
![Issue image](https://z-1-scontent-b-atl.xx.fbcdn.net/hphotos-xpa1/t31.0-8/10498263_10203374434030597_8938744975097680040_o.jpg)

**Comment by MrSchism** [comment]
Nothing on the screenshot actually works.

**Comment by RyanRiffle** [comment]
It hasn't loaded bootstrap. You have to use `make build-deps` or `bower install bootstrap`
